version: 0.2

phases:
  install:
    commands:
      - echo "Install phase..."
  pre_build:
    commands:
      - echo "Pre-build phase ..."
      - cd / terra-tier
      - pip3 install requirements.txt
      - find . -name newsread.service -type f
      - find . -name run.py -type f
      - find . -name application -type d
      - echo "Pre-build complete"
  build:
    commands:
      - echo "Build phase ..."
      - cp newsread.service /etc/systemd/system/newsread.service
      - systemctl daemon-reload
      - systemctl status newsread
  post_build:
    commands:
      - echo "Build successfully completed on $(date)"