version: 0.2

phases:
  install:
    commands:
      - echo "Install phase..."
  pre_build:
    commands:
      - echo "Pre-build phase ..."
      - pip3 install -r requirements.txt
      - find . -name newsread.service -type f
      - find . -name run.py -type f
      - find . -name application -type d
      - echo "Pre-build complete"
  build:
    commands:
      - echo "Build phase ..."
      - cp newsread.service /etc/systemd/system/newsread.service
      - service newsread start
  post_build:
    commands:
      - echo "Build completed on $(date)"